name: xdebug-test
recipe: drupal8

config:
  webroot: ./webroot
  drush: "*"
  via: nginx
  database: mysql
  php: '7.4'
  composer_version: "1.10.17"

services:
  appserver:
    xdebug: true
    config:
      php: .vscode/php.ini
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"

tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Enabling xdebug"
    user: root
  xdebug-off:
    service: appserver
    description: CUSTOM Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Disabling xdebug"
    user: root

